module.exports = {
  'likes': '{ likes, number} me gusta',
  'logout': 'Salir',
  'english': 'Inglés',
  'spanish': 'Español',
  'signup.subheading': 'Regístrate para ver fotos de tus amigos estudiando en Platzi',
  'signup.facebook': 'Iniciar sesión con Facebook',
  'signup.text': 'Iniciar sesion',
  'email': 'Correo electrónico',
  'username': 'Nombre de usuario',
  'fullname': 'Nombre completo',
  'password': 'Contraseña',
  'signup.call-to-action': 'Regístrate',
  'signup.have_account': '¿Tienes una cuenta?',
  'signin': 'Entrar',
  'signup.not-have-account': '¿No tenes cuenta?',
  'language': 'Idioma',
  'upload-picture': 'Subir foto',
  'upload': 'Subir'
}
